---
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: shortener-web
    env_file:
      - ./.env.example
    environment:
      - POSTGRES_HOST=db
      - MEMCACHED_HOST=cache
    depends_on:
      - db
      - cache

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.example

  cache:
    image: memcached:1-alpine

  nginx:
    image: nginx:1-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    env_file:
      - ./.env.example
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  postgres_data:
