---
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: shortener-web-dev
    command: uvicorn shortener.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app:ro
    env_file:
      - ./.env.example
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.example
    ports:
      - "5432:5432"

volumes:
  postgres_data:
