---
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: shortener-web
    env_file:
      - ./.env.example
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.example

  nginx:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    env_file:
      - ./.env.example
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  postgres_data:
