---
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: shortener-web
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    env_file:
      - ./ENV/.env.app
    environment:
      - MEMCACHED_HOST=cache

    depends_on:
      - cache


  cache:
    image: memcached:1-alpine
    restart: always


  ## NGINX-LE  https://github.com/nginx-le/nginx-le
  nginx:
    image: umputun/nginx-le:latest
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      - ./etc/ssl:/etc/nginx/ssl
      ## Ensure to copy 'etc/service-example.conf' to 'etc/nginx/service-shortener.conf' and modify it
      - ./etc/nginx/service-shortener.conf:/etc/nginx/service.conf
      # - ./etc/service-example.conf:/etc/nginx/service.conf
      # - ./etc/service-example-2.conf:/etc/nginx/service2.conf  # more services, should be service*.conf
      # - ./etc/stream-example-2.conf:/etc/nginx/stream2.conf  # more streams, should be stream*.conf
      # - ./etc/conf.d:/etc/nginx/conf.d-le  # configuration folder, all files from it will be added
      # - ./etc/stream.conf:/etc/nginx/stream.conf.d-le  # streams configuration folder, all files from it will be added

    ports:
      - "80:80"
      - "443:443"

    env_file:
      - ./ENV/.env.nginx  # Ensure to set LE_EMAIL and LE_FQDN variables
    environment:
      - TZ=UTC
      - LETSENCRYPT=true
      # - LE_EMAIL=name@example.com
      # - LE_FQDN=example.com,www.example.com
      ## - SSL_CERT=le-crt.pem
      ## - SSL_KEY=le-key.pem
      ## - SSL_CHAIN_CERT=le-chain-crt.pem

    depends_on:
      - web
