---
services:
  web:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    image: shortener-web
    env_file:
      - ./../.env.example
    environment:
      - POSTGRES_HOST=db
      - MEMCACHED_HOST=cache
    depends_on:
      - db
      - cache

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./../.env.example

  cache:
    image: memcached:1-alpine

  nginx:
    image: nginx:1-alpine
    volumes:
      - ./../etc/nginx/templates:/etc/nginx/templates
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  postgres_data:
